from app.models import db, Video

def seed_videos():
    video_1 = Video(title="Rally racing 1900s", summary="Good film of motor racing in France during the 1900s (c. 1905).", url="https://www.youtube.com/embed/D8k9ftSZn3I")
    video_2 = Video(title="WRC Rally 2021", summary="This is the best of WRC Rally 2021. These are the best crashes, action, and maximum attack moments from the year!", url="https://www.youtube.com/embed/D21WCUtkSDo")
    video_3 = Video(title="Monte Carlo Rally - In Their Own Words", summary="M-Sport Ford's star Frenchman scored a record-equaling eighth Mont Carlo Rally win at round one. In Exclusive interviews with DirtFish, tells us how he did it.", url="https://www.youtube.com/embed/Q_vSglNQr8Y")
    video_4 = Video(title="Toyota Rally1 Finland", summary="Toyota drivers Elfyn Evans, Esapekka Lappi and Kalle Rovanperä set about the Finnish forests as part of their Rally Sweden preparations earlier this week. The GR Yaris Rally1 works a treat in its winter colours...", url="https://www.youtube.com/embed/1bpWHyRCTjU")
    video_5 = Video(title="Monte Carlo Rally 2022", summary="Like pure engine noise? Don't go anywhere... here's the best action, crashes and pure sound from the Monte Carlo Rally 2022. See you in Sweden!", url="https://www.youtube.com/embed/3SotVx_fpio")
    video_6 = Video(title="2021 ARA Rally", summary="Follow along as we take a look at the incredible highlights of the 2021 ARA Rally season!", url="https://www.youtube.com/embed/epBAp8EnsFE")
    video_7 = Video(title="Road To WRC: Pre Season", summary="Sean Johnston heads to the Sainteloc HQ to work on a new seating position for the 2022 season.", url="https://www.youtube.com/embed/wTy1KFu-GVc")
    video_8 = Video(title="2021 Nitro RX North Florida", summary="Get a sneak peek at what you can expect from the 5th and final round of the 2021 Nitro Rallycross season this weekend at the FIRM in Florida!", url="https://www.youtube.com/embed/EBNbW42pYS4")
    video_9 = Video(title="SÉBASTIEN OGIER'S ALL-ACTION", summary="Sebastien Ogier and Julien Ingrassia claim their 8th WRC title here at the 2021 Rally Monza! Take a look at some of the highlights from over the past year that lead to this very special moment.", url="https://www.youtube.com/embed/h_QrqbQQHW8")
    video_10 = Video(title="Monte Carlo Winter Rally", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", url="https://www.youtube.com/embed/mYL8HrB7NCo")
    video_11 = Video(title="Nitro Rallycross Florida", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", url="https://www.youtube.com/embed/VNGF1uBtErc")
    video_12 = Video(title="Best of American Rally 2020", summary="These are the best moments of the 2020 ARA Rally season in America. Enjoy all the action, crashes, and maximum attack moments from this year!", url="https://www.youtube.com/embed/XT62vX4M4ro")
    video_13 = Video(title="Monte Carlo Rally: Exclusive Bloopers", summary="Rock climbing, Colin's sunglasses and Sean Johnston's pizza... The Monte Carlo Rally had it all!. Enjoy some of the moments which didn't quite make our traditional coverage. Want to see this from every rally? Let us know in the comments!", url="https://www.youtube.com/embed/rP7lIxrv-90")
    video_14 = Video(title="2021 Rally Monza - Highlights", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", url="https://www.youtube.com/embed/CWJbHkgckSA")
    video_15 = Video(title="2022 Race of Champions: Final", summary="The final between Sebastian Vettel and Sébastien Loeb for the 2022 Race of Champions. Two Sebs, from different motorsport categories, fighting it out for the Champion of Champions title. In this video I also included some interviews and pit (garage) footage, as well as the celebrations after the race", url="https://www.youtube.com/embed/tjJ6LMOse1w")
    video_16 = Video(title="Acropolis Rally Greece 2021", summary="DirtFish's Colin Clark gives us an update during day 3 here at WRC Acropolis Rally Greece 2021. We are seeing utter domination from Kalle Rovanperä thus far, can some of the other drivers hope to catch the 20-year-old Finn?", url="https://www.youtube.com/embed/qAlYwmaIWY8")
    video_17 = Video(title="Ojibwe Forests Rally 2021", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", url="https://www.youtube.com/embed/5NatdIHYJAc")
    video_18 = Video(title="Rally Estonia 2021", summary="These are the best crashes and action from Rally Estonia 2021. Enjoy this compilation of all the best maximum attack and flat out moments from the best drivers in the world!", url="https://www.youtube.com/embed/3xZqCqIkWBc")
    video_19 = Video(title="Rallycross Minnesota 2021", summary="The second round of Nitro Rallycross is here!! This time we are in Minnesota at the ERX Motor Park at the fastest track of the season. Tune in this weekend as we will be bringing you all the news, highlights, and drama.", url="https://www.youtube.com/embed/7OAcqx8eVLY")
    video_20 = Video(title="2021 Oregon Trail Rally", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", url="https://www.youtube.com/embed/TDGhBZBK7eo")
    video_21 = Video(title="Performance Rally 2021", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", url="https://www.youtube.com/embed/xsPVmpuTPaA")
    video_22 = Video(title="WRC Rally Estonia 2021", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", url="https://www.youtube.com/embed/YbzsswHHrv4")
    video_23 = Video(title="Ypres Rally Belgium 2021", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", url="https://www.youtube.com/embed/IrkNkLoSNn8")
    video_24 = Video(title="Ohio Forest Rally 2021", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", url="https://www.youtube.com/embed/OuGfM8QTA2g")
    video_25 = Video(title="Subaru WRX STI Onboard", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", url="https://www.youtube.com/embed/IuTFqjK_P3A")
    video_26 = Video(title="Rally Di Roma Capitale 2020", summary="The final day of Rally Di Roma Capitale 2020 was exciting all the way until the end when Alexey Lukyanuk was crowned the victor. Plus, Colin Clark searches Rome for someone who can help him review some footage.", url="https://www.youtube.com/embed/fo6MuZWMr5s")
    video_27 = Video(title="Rally Italy 2020", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", url="https://www.youtube.com/embed/i4x9oi3HykA")
    video_28 = Video(title="Hyundai WRC Factory Tour", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", url="https://www.youtube.com/embed/XUAyqepXKCQ")
    video_29 = Video(title="The Ford Escort Cosworth", summary="Colin Clark chats with Ken Block before the start of WRC Mexico about his Ford RS Cosworth and why WRC Mexico is one of his favorite rallies.", url="https://www.youtube.com/embed/lL3EoUYVr0o")
    video_30 = Video(title="Sam Albert DooWop Rally", summary="Take a ride on the bumper of Sam Albert and Michelle Miller's Subaru STI for one of the Doo Wop Rally stages last weekend!", url="https://www.youtube.com/embed/6rQKXbcylRo")
    video_31 = Video(title="2021 Oregon Trail Rally", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", url="https://www.youtube.com/embed/ZoOBmXRJhp8")
    video_32 = Video(title="Rally Greece 2021", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", url="https://www.youtube.com/embed/0cN1u5rDrYU")
    video_33 = Video(title="Ogier Reflects on WRC Career", summary="DirtFish's Colin Clark chats with Sébastien Ogier to get some final words on his wonderful career up until this point of his 8th WRC Title...", url="https://www.youtube.com/embed/keKzLWu9Br0")
    video_34 = Video(title="2021 WRC Rally Spain", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", url="https://www.youtube.com/embed/Do0g17tq_DA")
    video_35 = Video(title="2021 Ojibwe Forests Rally", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", url="https://www.youtube.com/embed/AuXxsXXvzQQ")
    video_36 = Video(title="WRC Rally Italy 2021", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", url="https://www.youtube.com/embed/xcNIrxY7gK8")
    video_37 = Video(title="Colin McRae Tribute", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", url="https://www.youtube.com/embed/M2-6LneqzLs")
    video_38 = Video(title="Historic Cars of Rally", summary="The best of historic rally cars, the Audi quattro sport, the MG Metro 6 r4, the Escort mk 2 bda, the 205 T 16 , the Talbot lotus , the Toyota celica, etc....", url="https://www.youtube.com/embed/LOr0r8-qbrg")
    video_39 = Video(title="Hannu Mikkola Tribute", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", url="https://www.youtube.com/embed/D-RNiUs1Uuw")
    video_40 = Video(title="CIRC Olympus Rally 2015", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", url="https://www.youtube.com/embed/Q9fHiv3HyJ0")

    db.session.add(video_1)
    db.session.add(video_2)
    db.session.add(video_3)
    db.session.add(video_4)
    db.session.add(video_5)
    db.session.add(video_6)
    db.session.add(video_7)
    db.session.add(video_8)
    db.session.add(video_9)
    db.session.add(video_10)
    db.session.add(video_11)
    db.session.add(video_12)
    db.session.add(video_13)
    db.session.add(video_14)
    db.session.add(video_15)
    db.session.add(video_16)
    db.session.add(video_17)
    db.session.add(video_18)
    db.session.add(video_19)
    db.session.add(video_20)
    db.session.add(video_21)
    db.session.add(video_22)
    db.session.add(video_23)
    db.session.add(video_24)
    db.session.add(video_25)
    db.session.add(video_26)
    db.session.add(video_27)
    db.session.add(video_28)
    db.session.add(video_29)
    db.session.add(video_30)
    db.session.add(video_31)
    db.session.add(video_32)
    db.session.add(video_33)
    db.session.add(video_34)
    db.session.add(video_35)
    db.session.add(video_36)
    db.session.add(video_37)
    db.session.add(video_38)
    db.session.add(video_39)
    db.session.add(video_40)

    db.session.commit()

def undo_videos():
    db.session.execute('TRUNCATE videos RESTART IDENTITY CASCADE;')
    db.session.commit()
