from app.models import db, Video

def seed_videos():

    video_1 = Video(title="Rally racing 1900s", summary="Good film of motor racing in France during the 1900s (c. 1905).", list_id=1, src="https://www.youtube.com/embed/D8k9ftSZn3I")
    video_2 = Video(title="WRC Rally 2021", summary="This is the best of WRC Rally 2021. These are the best crashes, action, and maximum attack moments from the year!", list_id=1, src="https://www.youtube.com/embed/D21WCUtkSDo")
    video_3 = Video(title="Monte Carlo Rally - In Their Own Words", summary="M-Sport Ford's star Frenchman scored a record-equaling eighth Mont Carlo Rally win at round one. In Exclusive interviews with DirtFish, tells us how he did it.", list_id=1, src="https://www.youtube.com/embed/Q_vSglNQr8Y")
    video_4 = Video(title="Toyota Rally1 Finland", summary="Toyota drivers Elfyn Evans, Esapekka Lappi and Kalle Rovanperä set about the Finnish forests as part of their Rally Sweden preparations earlier this week. The GR Yaris Rally1 works a treat in its winter colours...", list_id=1, src="https://www.youtube.com/embed/1bpWHyRCTjU")
    video_5 = Video(title="Monte Carlo Rally 2022", summary="Like pure engine noise? Don't go anywhere... here's the best action, crashes and pure sound from the Monte Carlo Rally 2022. See you in Sweden!", list_id=1, src="https://www.youtube.com/embed/3SotVx_fpio")
    video_6 = Video(title="2021 ARA Rally", summary="Follow along as we take a look at the incredible highlights of the 2021 ARA Rally season!", list_id=1, src="https://www.youtube.com/embed/epBAp8EnsFE")
    video_7 = Video(title="Road To WRC: Pre Season", summary="Sean Johnston heads to the Sainteloc HQ to work on a new seating position for the 2022 season.", src="https://www.youtube.com/embed/wTy1KFu-GVc")
    video_8 = Video(title="2021 Nitro RX North Florida", summary="Get a sneak peek at what you can expect from the 5th and final round of the 2021 Nitro Rallycross season this weekend at the FIRM in Florida!", src="https://www.youtube.com/embed/EBNbW42pYS4")
    video_9 = Video(title="SÉBASTIEN OGIER'S ALL-ACTION", summary="Sebastien Ogier and Julien Ingrassia claim their 8th WRC title here at the 2021 Rally Monza! Take a look at some of the highlights from over the past year that lead to this very special moment.", src="https://www.youtube.com/embed/h_QrqbQQHW8")
    video_10 = Video(title="Monte Carlo Winter Rally", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", src="https://www.youtube.com/embed/mYL8HrB7NCo")
    video_11 = Video(title="Nitro Rallycross Florida", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", src="https://www.youtube.com/embed/VNGF1uBtErc")
    video_12 = Video(title="Best of American Rally 2020", summary="These are the best moments of the 2020 ARA Rally season in America. Enjoy all the action, crashes, and maximum attack moments from this year!", src="https://www.youtube.com/embed/XT62vX4M4ro")
    video_13 = Video(title="Monte Carlo Rally: Exclusive Bloopers", summary="Rock climbing, Colin's sunglasses and Sean Johnston's pizza... The Monte Carlo Rally had it all!. Enjoy some of the moments which didn't quite make our traditional coverage. Want to see this from every rally? Let us know in the comments!", src="https://www.youtube.com/embed/rP7lIxrv-90")
    video_14 = Video(title="2021 Rally Monza - Highlights", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", src="https://www.youtube.com/embed/CWJbHkgckSA")
    video_15 = Video(title="2022 Race of Champions: Final", summary="The final between Sebastian Vettel and Sébastien Loeb for the 2022 Race of Champions. Two Sebs, from different motorsport categories, fighting it out for the Champion of Champions title. In this video I also included some interviews and pit (garage) footage, as well as the celebrations after the race", src="https://www.youtube.com/embed/tjJ6LMOse1w")
    video_16 = Video(title="Acropolis Rally Greece 2021", summary="DirtFish's Colin Clark gives us an update during day 3 here at WRC Acropolis Rally Greece 2021. We are seeing utter domination from Kalle Rovanperä thus far, can some of the other drivers hope to catch the 20-year-old Finn?", src="https://www.youtube.com/embed/qAlYwmaIWY8")
    video_17 = Video(title="Ojibwe Forests Rally 2021", summary="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", src="https://www.youtube.com/embed/5NatdIHYJAc")
    video_18 = Video(title="Rally Estonia 2021", summary="These are the best crashes and action from Rally Estonia 2021. Enjoy this compilation of all the best maximum attack and flat out moments from the best drivers in the world!", src="https://www.youtube.com/embed/3xZqCqIkWBc")
    video_19 = Video(title="", summary="", src="")
    video_20 = Video(title="", summary="", src="")
    video_21 = Video(title="", summary="", src="")
    video_22 = Video(title="", summary="", src="")
    video_23 = Video(title="", summary="", src="")
    video_24 = Video(title="", summary="", src="")
    video_25 = Video(title="", summary="", src="")
    video_26 = Video(title="", summary="", src="")
    video_27 = Video(title="", summary="", src="")
    video_28 = Video(title="", summary="", src="")
    video_29 = Video(title="", summary="", src="")
    video_30 = Video(title="", summary="", src="")
    video_31 = Video(title="", summary="", src="")
    video_32 = Video(title="", summary="", src="")
    video_33 = Video(title="", summary="", src="")
    video_34 = Video(title="", summary="", src="")
    video_35 = Video(title="", summary="", src="")
    video_36 = Video(title="", summary="", src="")
    video_37 = Video(title="", summary="", src="")
    video_38 = Video(title="", summary="", src="")
    video_39 = Video(title="", summary="", src="")
    video_40 = Video(title="", summary="", src="")
    video_41 = Video(title="", summary="", src="")
    video_42 = Video(title="", summary="", src="")
    video_43 = Video(title="", summary="", src="")
    video_44 = Video(title="", summary="", src="")
    video_45 = Video(title="", summary="", src="")
