"""empty message

Revision ID: 071455d56c06
Revises: 745d3e607d9d
Create Date: 2022-02-22 11:59:56.060122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071455d56c06'
down_revision = '745d3e607d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lists_video_id_fkey', 'lists', type_='foreignkey')
    op.drop_column('lists', 'video_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('lists_video_id_fkey', 'lists', 'videos', ['video_id'], ['id'])
    # ### end Alembic commands ###
