"""empty message

Revision ID: 57d09a379365
Revises: 071455d56c06
Create Date: 2022-02-22 12:01:14.747330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d09a379365'
down_revision = '071455d56c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('video_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lists', 'videos', ['video_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lists', type_='foreignkey')
    op.drop_column('lists', 'video_id')
    # ### end Alembic commands ###
