"""empty message

Revision ID: 70828e48e734
Revises: 57d09a379365
Create Date: 2022-02-24 19:34:05.310464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70828e48e734'
down_revision = '57d09a379365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_to_videos',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('list_id', 'video_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('list_to_videos')
    # ### end Alembic commands ###
